; Include macro and constant definitions. 
; Macro definitions are taken from the pret disassembly, but excludes VC symbols
INCLUDE "include/incpret/c/constants/charmap_jp.asm"
INCLUDE "include/incpret/gs/constants/charmap.asm"

INCLUDE "include/incpret/c/macros/asserts.asm"
INCLUDE "include/incpret/c/macros/const.asm"
INCLUDE "include/incpret/c/macros/predef.asm"
INCLUDE "include/incpret/c/macros/farcall.asm"
INCLUDE "include/incpret/c/macros/data.asm"
INCLUDE "include/incpret/c/macros/code.asm"
INCLUDE "include/incpret/c/macros/gfx.asm"
INCLUDE "include/incpret/c/macros/coords.asm"
INCLUDE "include/incpret/c/macros/vc.asm"

INCLUDE "include/incpret/c/macros/scripts/audio.asm"
INCLUDE "include/incpret/c/macros/scripts/maps.asm"
INCLUDE "include/incpret/c/macros/scripts/events_jp.asm"
INCLUDE "include/incpret/c/macros/scripts/text.asm"
INCLUDE "include/incpret/c/macros/scripts/movement.asm"
INCLUDE "include/incpret/c/macros/scripts/battle_commands.asm"
INCLUDE "include/incpret/c/macros/scripts/battle_anims.asm"
INCLUDE "include/incpret/c/macros/scripts/oam_anims.asm"
INCLUDE "include/incpret/c/macros/scripts/pic_anims.asm"

INCLUDE "include/incpret/c/constants/hardware.inc"
INCLUDE "include/incpret/c/constants/deco_constants.asm"
INCLUDE "include/incpret/c/constants/ram_constants.asm"
INCLUDE "include/incpret/c/constants/misc_constants.asm"
INCLUDE "include/incpret/c/constants/input_constants.asm"
INCLUDE "include/incpret/c/constants/gfx_constants.asm"
INCLUDE "include/incpret/c/constants/text_constants.asm"
INCLUDE "include/incpret/c/constants/audio_constants.asm"
INCLUDE "include/incpret/c/constants/battle_anim_constants.asm"
INCLUDE "include/incpret/c/constants/battle_constants.asm"
INCLUDE "include/incpret/c/constants/collision_constants.asm"
INCLUDE "include/incpret/c/constants/credits_constants.asm"
INCLUDE "include/incpret/c/constants/cry_constants.asm"
INCLUDE "include/incpret/c/constants/engine_flags.asm"
INCLUDE "include/incpret/c/constants/event_flags.asm"
INCLUDE "include/incpret/c/constants/icon_constants.asm"
INCLUDE "include/incpret/c/constants/landmark_constants.asm"
INCLUDE "include/incpret/c/constants/map_constants.asm"
INCLUDE "include/incpret/c/constants/map_data_constants.asm"
INCLUDE "include/incpret/c/constants/map_object_constants.asm"
INCLUDE "include/incpret/c/constants/map_setup_constants.asm"
INCLUDE "include/incpret/c/constants/mart_constants.asm"
INCLUDE "include/incpret/c/constants/menu_constants.asm"
INCLUDE "include/incpret/c/constants/mobile_constants.asm"
INCLUDE "include/incpret/c/constants/move_constants.asm"
INCLUDE "include/incpret/c/constants/move_effect_constants.asm"
INCLUDE "include/incpret/c/constants/item_constants.asm"
INCLUDE "include/incpret/c/constants/item_data_constants.asm"
INCLUDE "include/incpret/c/constants/music_constants.asm"
INCLUDE "include/incpret/c/constants/npc_trade_constants.asm"
INCLUDE "include/incpret/c/constants/phone_constants.asm"
INCLUDE "include/incpret/c/constants/pokemon_constants.asm"
INCLUDE "include/incpret/c/constants/pokemon_data_constants.asm"
INCLUDE "include/incpret/c/constants/printer_constants.asm"
INCLUDE "include/incpret/c/constants/radio_constants.asm"
INCLUDE "include/incpret/c/constants/scgb_constants.asm"
INCLUDE "include/incpret/c/constants/script_constants.asm"
INCLUDE "include/incpret/c/constants/serial_constants.asm"
INCLUDE "include/incpret/c/constants/sfx_constants.asm"
INCLUDE "include/incpret/c/constants/sprite_anim_constants.asm"
INCLUDE "include/incpret/c/constants/sprite_constants.asm"
INCLUDE "include/incpret/c/constants/sprite_data_constants.asm"
INCLUDE "include/incpret/c/constants/tileset_constants.asm"
INCLUDE "include/incpret/c/constants/trainer_constants.asm"
INCLUDE "include/incpret/c/constants/trainer_data_constants.asm"
INCLUDE "include/incpret/c/constants/type_constants.asm"
INCLUDE "include/incpret/c/constants/battle_tower_constants.asm"

INCLUDE "include/incpret/c/macros/legacy.asm"

; Include sym and custom symbols
INCLUDE "include/constants/hardware.inc"
INCLUDE "include/incsym/pokecrystal_jp.inc"
INCLUDE "include/inccustom/customcrystal_jp.inc"