; Include macro and constant definitions. 
; Macro definitions are taken from the pret disassembly, but excludes VC symbols
INCLUDE "include/incpret/gs/constants/charmap.asm"

INCLUDE "include/incpret/gs/macros/asserts.asm"
INCLUDE "include/incpret/gs/macros/const.asm"
INCLUDE "include/incpret/gs/macros/predef.asm"
INCLUDE "include/incpret/gs/macros/farcall.asm"
INCLUDE "include/incpret/gs/macros/data.asm"
INCLUDE "include/incpret/gs/macros/code.asm"
INCLUDE "include/incpret/gs/macros/gfx.asm"
INCLUDE "include/incpret/gs/macros/coords.asm"
INCLUDE "include/incpret/gs/macros/vc.asm"

INCLUDE "include/incpret/gs/macros/scripts/audio.asm"
INCLUDE "include/incpret/gs/macros/scripts/maps.asm"
INCLUDE "include/incpret/gs/macros/scripts/events.asm"
INCLUDE "include/incpret/gs/macros/scripts/text.asm"
INCLUDE "include/incpret/gs/macros/scripts/movement.asm"
INCLUDE "include/incpret/gs/macros/scripts/battle_commands.asm"
INCLUDE "include/incpret/gs/macros/scripts/battle_anims.asm"
INCLUDE "include/incpret/gs/macros/scripts/oam_anims.asm"

INCLUDE "include/incpret/gs/constants/hardware.inc"

INCLUDE "include/incpret/gs/constants/deco_constants.asm"
INCLUDE "include/incpret/gs/constants/ram_constants.asm"
INCLUDE "include/incpret/gs/constants/misc_constants.asm"
INCLUDE "include/incpret/gs/constants/input_constants.asm"
INCLUDE "include/incpret/gs/constants/gfx_constants.asm"
INCLUDE "include/incpret/gs/constants/text_constants.asm"
INCLUDE "include/incpret/gs/constants/audio_constants.asm"
INCLUDE "include/incpret/gs/constants/battle_anim_constants.asm"
INCLUDE "include/incpret/gs/constants/battle_constants.asm"
INCLUDE "include/incpret/gs/constants/collision_constants.asm"
INCLUDE "include/incpret/gs/constants/credits_constants.asm"
INCLUDE "include/incpret/gs/constants/cry_constants.asm"
INCLUDE "include/incpret/gs/constants/engine_flags.asm"
INCLUDE "include/incpret/gs/constants/event_flags.asm"
INCLUDE "include/incpret/gs/constants/icon_constants.asm"
INCLUDE "include/incpret/gs/constants/landmark_constants.asm"
INCLUDE "include/incpret/gs/constants/map_constants.asm"
INCLUDE "include/incpret/gs/constants/map_data_constants.asm"
INCLUDE "include/incpret/gs/constants/map_object_constants.asm"
INCLUDE "include/incpret/gs/constants/map_setup_constants.asm"
INCLUDE "include/incpret/gs/constants/mart_constants.asm"
INCLUDE "include/incpret/gs/constants/menu_constants.asm"
INCLUDE "include/incpret/gs/constants/move_constants.asm"
INCLUDE "include/incpret/gs/constants/move_effect_constants.asm"
INCLUDE "include/incpret/gs/constants/item_constants.asm"
INCLUDE "include/incpret/gs/constants/item_data_constants.asm"
INCLUDE "include/incpret/gs/constants/music_constants.asm"
INCLUDE "include/incpret/gs/constants/npc_trade_constants.asm"
INCLUDE "include/incpret/gs/constants/phone_constants.asm"
INCLUDE "include/incpret/gs/constants/pokemon_constants.asm"
INCLUDE "include/incpret/gs/constants/pokemon_data_constants.asm"
INCLUDE "include/incpret/gs/constants/printer_constants.asm"
INCLUDE "include/incpret/gs/constants/radio_constants.asm"
INCLUDE "include/incpret/gs/constants/scgb_constants.asm"
INCLUDE "include/incpret/gs/constants/script_constants.asm"
INCLUDE "include/incpret/gs/constants/serial_constants.asm"
INCLUDE "include/incpret/gs/constants/sfx_constants.asm"
INCLUDE "include/incpret/gs/constants/sprite_anim_constants.asm"
INCLUDE "include/incpret/gs/constants/sprite_constants.asm"
INCLUDE "include/incpret/gs/constants/sprite_data_constants.asm"
INCLUDE "include/incpret/gs/constants/tileset_constants.asm"
INCLUDE "include/incpret/gs/constants/trainer_constants.asm"
INCLUDE "include/incpret/gs/constants/trainer_data_constants.asm"
INCLUDE "include/incpret/gs/constants/type_constants.asm"

INCLUDE "include/incpret/gs/macros/legacy.asm"

; Include sym and custom symbols
INCLUDE "include/constants/hardware.inc"
INCLUDE "include/incsym/pokegold_sp.inc"
INCLUDE "include/inccustom/customgold_sp.inc"