#ifndef SCRIPT_H
#define SCRIPT_H

#include "pokemon_party.h"
#include "script_builder.h"

#define JAPAN_WONDER_CARD_OFFSET ((GAMECODE == FIRERED || GAMECODE == LEAFGREEN) ? 0x0384 : 0x0490)
#define JAPAN_WONDER_CARD_OFFSET_FRLG 0x0384
#define JAPAN_WONDER_CARD_OFFSET_EMER 0x0490

#define INTER_WONDER_CARD_OFFSET ((GAMECODE == FIRERED || GAMECODE == LEAFGREEN) ? 0x0460 : 0x056C)
#define INTER_WONDER_CARD_OFFSET_FRLG 0x0460
#define INTER_WONDER_CARD_OFFSET_EMER 0x056C

#define EVENT_SCRIPT_DATA_OFFSET ((GAMECODE == RUBY || GAMECODE == SAPPHIRE) ? 0x0810 : ((GAMECODE == FIRERED || GAMECODE == LEAFGREEN) ? 0x079C : 0x08A8))
#define EVENT_SCRIPT_DATA_OFFSET_RUSA 0x0810
#define EVENT_SCRIPT_DATA_OFFSET_FRLG 0x079C
#define EVENT_SCRIPT_DATA_OFFSET_EMER 0x08A8

void inject_mystery(Pokemon incoming_party_array[]);

#endif