#include "exp_groups.h"
#include <tonc.h>

const u32 EXP_TYPES[6] = {
    fast_max,
    med_fast_max,
    med_slow_max,
    slow_max};

u32 get_max_exp(int index_num)
{
    return EXP_TYPES[EXP_MAX[index_num]];
}

const u8 EXP_MAX[251] = {
    2, // Bulbasaur
    2, // Ivysaur
    2, // Venusaur
    2, // Charmander
    2, // Charmeleon
    2, // Charizard
    2, // Squirtle
    2, // Wartortle
    2, // Blastoise
    1, // Caterpie
    1, // Metapod
    1, // Butterfree
    1, // Weedle
    1, // Kakuna
    1, // Beedrill
    2, // Pidgey
    2, // Pidgeotto
    2, // Pidgeot
    1, // Rattata
    1, // Raticate
    1, // Spearow
    1, // Fearow
    1, // Ekans
    1, // Arbok
    1, // Pikachu
    1, // Raichu
    1, // Sandshrew
    1, // Sandslash
    2, // Nidoran♀
    2, // Nidorina
    2, // Nidoqueen
    2, // Nidoran♂
    2, // Nidorino
    2, // Nidoking
    0, // Clefairy
    0, // Clefable
    1, // Vulpix
    1, // Ninetales
    0, // Jigglypuff
    0, // Wigglytuff
    1, // Zubat
    1, // Golbat
    2, // Oddish
    2, // Gloom
    2, // Vileplume
    1, // Paras
    1, // Parasect
    1, // Venonat
    1, // Venomoth
    1, // Diglett
    1, // Dugtrio
    1, // Meowth
    1, // Persian
    1, // Psyduck
    1, // Golduck
    1, // Mankey
    1, // Primeape
    3, // Growlithe
    3, // Arcanine
    2, // Poliwag
    2, // Poliwhirl
    2, // Poliwrath
    2, // Abra
    2, // Kadabra
    2, // Alakazam
    2, // Machop
    2, // Machoke
    2, // Machamp
    2, // Bellsprout
    2, // Weepinbell
    2, // Victreebel
    3, // Tentacool
    3, // Tentacruel
    2, // Geodude
    2, // Graveler
    2, // Golem
    1, // Ponyta
    1, // Rapidash
    1, // Slowpoke
    1, // Slowbro
    1, // Magnemite
    1, // Magneton
    1, // Farfetch'd
    1, // Doduo
    1, // Dodrio
    1, // Seel
    1, // Dewgong
    1, // Grimer
    1, // Muk
    3, // Shellder
    3, // Cloyster
    2, // Gastly
    2, // Haunter
    2, // Gengar
    1, // Onix
    1, // Drowzee
    1, // Hypno
    1, // Krabby
    1, // Kingler
    1, // Voltorb
    1, // Electrode
    3, // Exeggcute
    3, // Exeggutor
    1, // Cubone
    1, // Marowak
    1, // Hitmonlee
    1, // Hitmonchan
    1, // Lickitung
    1, // Koffing
    1, // Weezing
    3, // Rhyhorn
    3, // Rhydon
    0, // Chansey
    1, // Tangela
    1, // Kangaskhan
    1, // Horsea
    1, // Seadra
    1, // Goldeen
    1, // Seaking
    3, // Staryu
    3, // Starmie
    1, // Mr. Mime
    1, // Scyther
    1, // Jynx
    1, // Electabuzz
    1, // Magmar
    3, // Pinsir
    3, // Tauros
    3, // Magikarp
    3, // Gyarados
    3, // Lapras
    1, // Ditto
    1, // Eevee
    1, // Vaporeon
    1, // Jolteon
    1, // Flareon
    1, // Porygon
    1, // Omanyte
    1, // Omastar
    1, // Kabuto
    1, // Kabutops
    3, // Aerodactyl
    3, // Snorlax
    3, // Articuno
    3, // Zapdos
    3, // Moltres
    3, // Dratini
    3, // Dragonair
    3, // Dragonite
    3, // Mewtwo
    2, // Mew
    2, // Chikorita
    2, // Bayleef
    2, // Meganium
    2, // Cyndaquil
    2, // Quilava
    2, // Typhlosion
    2, // Totodile
    2, // Croconaw
    2, // Feraligatr
    1, // Sentret
    1, // Furret
    1, // Hoothoot
    1, // Noctowl
    0, // Ledyba
    0, // Ledian
    0, // Spinarak
    0, // Ariados
    1, // Crobat
    3, // Chinchou
    3, // Lanturn
    1, // Pichu
    0, // Cleffa
    0, // Igglybuff
    0, // Togepi
    0, // Togetic
    1, // Natu
    1, // Xatu
    2, // Mareep
    2, // Flaaffy
    2, // Ampharos
    2, // Bellossom
    0, // Marill
    0, // Azumarill
    1, // Sudowoodo
    2, // Politoed
    2, // Hoppip
    2, // Skiploom
    2, // Jumpluff
    0, // Aipom
    2, // Sunkern
    2, // Sunflora
    1, // Yanma
    1, // Wooper
    1, // Quagsire
    1, // Espeon
    1, // Umbreon
    2, // Murkrow
    1, // Slowking
    0, // Misdreavus
    1, // Unown
    1, // Wobbuffet
    1, // Girafarig
    1, // Pineco
    1, // Forretress
    1, // Dunsparce
    2, // Gligar
    1, // Steelix
    0, // Snubbull
    0, // Granbull
    1, // Qwilfish
    1, // Scizor
    2, // Shuckle
    3, // Heracross
    2, // Sneasel
    1, // Teddiursa
    1, // Ursaring
    1, // Slugma
    1, // Magcargo
    3, // Swinub
    3, // Piloswine
    0, // Corsola
    1, // Remoraid
    1, // Octillery
    0, // Delibird
    3, // Mantine
    3, // Skarmory
    3, // Houndour
    3, // Houndoom
    1, // Kingdra
    1, // Phanpy
    1, // Donphan
    1, // Porygon2
    3, // Stantler
    0, // Smeargle
    1, // Tyrogue
    1, // Hitmontop
    1, // Smoochum
    1, // Elekid
    1, // Magby
    3, // Miltank
    0, // Blissey
    3, // Raikou
    3, // Entei
    3, // Suicune
    3, // Larvitar
    3, // Pupitar
    3, // Tyranitar
    3, // Lugia
    3, // Ho-Oh
    2, // Celebi
};
